export interface Country {
  code: string,
  emoji: string,
  label: string,
  phone: string,
  phoneFormats?: Array<string | number>,
}

interface RawCountry {
  code: string,
  emoji: string,
  label: string,
  phone: string,
  phoneLengths: number[],
}

const formatsForLengths = {
  4: 'dd dd',
  5: 'dd ddd',
  6: 'ddd ddd',
  7: 'ddd dddd',
  8: 'dddd dddd',
  9: 'dddd ddddd',
  10: 'ddd ddd dddd',
};

function getFormatForLength(length: number): string {
  if (length in formatsForLengths) {
    return (formatsForLengths as any)[length];
  }

  const blockSize = 4;
  const delimiter = ' ';
  const blocksCount = Math.ceil(length / blockSize);
  let format = '';
  let dCount: number;
  for (let i = 0; i < blocksCount; ++i) {
    if (i === 0) {
      dCount = (length % blockSize) || blockSize;
    } else {
      format += delimiter;
      dCount = blockSize;
    }
    for (let j = 0; j < dCount; ++j) {
      format += 'd';
    }
  }
  return format;
}

// Data based on:
// https://github.com/AfterShip/phone/blob/ebd78d7763035ce447c87287936f196d5cc90eec/lib/iso3166Data.js
// https://github.com/risan/country-flag-emoji/blob/bc2529b43dc50303f29ac22138ced0a5466e5126/src/data.js
const rawCountries: RawCountry[] = [
  { code: 'us', label: 'United States', emoji: '🇺🇸', phone: '+1', phoneLengths: [10] },
  { code: 'aw', label: 'Aruba', emoji: '🇦🇼', phone: '+297', phoneLengths: [7] },
  { code: 'af', label: 'Afghanistan', emoji: '🇦🇫', phone: '+93 7', phoneLengths: [8] },
  { code: 'ao', label: 'Angola', emoji: '🇦🇴', phone: '+244 9', phoneLengths: [8] },
  { code: 'ai', label: 'Anguilla', emoji: '🇦🇮', phone: '+1 264', phoneLengths: [7] },
  { code: 'ax', label: 'Åland Islands', emoji: '🇦🇽', phone: '+358 18', phoneLengths: [4, 5, 6] },
  { code: 'al', label: 'Albania', emoji: '🇦🇱', phone: '+355 6', phoneLengths: [8] },
  { code: 'ad', label: 'Andorra', emoji: '🇦🇩', phone: '+376', phoneLengths: [6] },
  { code: 'ae', label: 'United Arab Emirates', emoji: '🇦🇪', phone: '+971 5', phoneLengths: [8] },
  { code: 'ar', label: 'Argentina', emoji: '🇦🇷', phone: '+54', phoneLengths: [10] },
  { code: 'am', label: 'Armenia', emoji: '🇦🇲', phone: '+374', phoneLengths: [8] },
  { code: 'as', label: 'American Samoa', emoji: '🇦🇸', phone: '+1 684', phoneLengths: [7] },
  { code: 'ag', label: 'Antigua and Barbuda', emoji: '🇦🇬', phone: '+1 2687', phoneLengths: [6] },
  { code: 'au', label: 'Australia', emoji: '🇦🇺', phone: '+61 4', phoneLengths: [8] },
  { code: 'at', label: 'Austria', emoji: '🇦🇹', phone: '+43 6', phoneLengths: [9, 10, 11, 12, 13] },
  { code: 'az', label: 'Azerbaijan', emoji: '🇦🇿', phone: '+994', phoneLengths: [9] },
  { code: 'bi', label: 'Burundi', emoji: '🇧🇮', phone: '+257', phoneLengths: [8] },
  { code: 'be', label: 'Belgium', emoji: '🇧🇪', phone: '+32', phoneLengths: [9, 8] },
  { code: 'bj', label: 'Benin', emoji: '🇧🇯', phone: '+229 9', phoneLengths: [7] },
  { code: 'bf', label: 'Burkina Faso', emoji: '🇧🇫', phone: '+226', phoneLengths: [8] },
  { code: 'bd', label: 'Bangladesh', emoji: '🇧🇩', phone: '+880 1', phoneLengths: [7, 8, 9] },
  { code: 'bg', label: 'Bulgaria', emoji: '🇧🇬', phone: '+359', phoneLengths: [8, 9] },
  { code: 'bh', label: 'Bahrain', emoji: '🇧🇭', phone: '+973 3', phoneLengths: [7] },
  { code: 'bs', label: 'Bahamas', emoji: '🇧🇸', phone: '+1 242', phoneLengths: [7] },
  { code: 'ba', label: 'Bosnia and Herzegovina', emoji: '🇧🇦', phone: '+387 6', phoneLengths: [7] },
  { code: 'by', label: 'Belarus', emoji: '🇧🇾', phone: '+375', phoneLengths: [9] },
  { code: 'bz', label: 'Belize', emoji: '🇧🇿', phone: '+501 6', phoneLengths: [6] },
  { code: 'bm', label: 'Bermuda', emoji: '🇧🇲', phone: '+1 441', phoneLengths: [7] },
  { code: 'bo', label: 'Bolivia', emoji: '🇧🇴', phone: '+591 7', phoneLengths: [7] },
  { code: 'br', label: 'Brazil', emoji: '🇧🇷', phone: '+55', phoneLengths: [10, 11] },
  { code: 'bb', label: 'Barbados', emoji: '🇧🇧', phone: '+1 246', phoneLengths: [7] },
  { code: 'bn', label: 'Brunei Darussalam', emoji: '🇧🇳', phone: '+673', phoneLengths: [7] },
  { code: 'bt', label: 'Bhutan', emoji: '🇧🇹', phone: '+975 17', phoneLengths: [6] },
  { code: 'bw', label: 'Botswana', emoji: '🇧🇼', phone: '+267 7', phoneLengths: [7] },
  { code: 'cf', label: 'Central African Republic', emoji: '🇨🇫', phone: '+236 7', phoneLengths: [7] },
  { code: 'ca', label: 'Canada', emoji: '🇨🇦', phone: '+1', phoneLengths: [10] },
  { code: 'ch', label: 'Switzerland', emoji: '🇨🇭', phone: '+41 7', phoneLengths: [8] },
  { code: 'cl', label: 'Chile', emoji: '🇨🇱', phone: '+56 9', phoneLengths: [8] },
  { code: 'cn', label: 'China', emoji: '🇨🇳', phone: '+86 1', phoneLengths: [10] },
  { code: 'ci', label: 'Côte D\'Ivoire', emoji: '🇨🇮', phone: '+225', phoneLengths: [8] },
  { code: 'cm', label: 'Cameroon', emoji: '🇨🇲', phone: '+237 6', phoneLengths: [8] },
  { code: 'cd', label: 'Congo, The Democratic Republic Of The', emoji: '🇨🇩', phone: '+243', phoneLengths: [9] },
  { code: 'cg', label: 'Congo', emoji: '🇨🇬', phone: '+242 0', phoneLengths: [8] },
  { code: 'ck', label: 'Cook Islands', emoji: '🇨🇰', phone: '+682', phoneLengths: [5] },
  { code: 'co', label: 'Colombia', emoji: '🇨🇴', phone: '+57 3', phoneLengths: [9] },
  { code: 'km', label: 'Comoros', emoji: '🇰🇲', phone: '+269', phoneLengths: [7] },
  { code: 'cv', label: 'Cape Verde', emoji: '🇨🇻', phone: '+238', phoneLengths: [7] },
  { code: 'cr', label: 'Costa Rica', emoji: '🇨🇷', phone: '+506', phoneLengths: [8] },
  { code: 'cu', label: 'Cuba', emoji: '🇨🇺', phone: '+53 5', phoneLengths: [7] },
  { code: 'ky', label: 'Cayman Islands', emoji: '🇰🇾', phone: '+1 345', phoneLengths: [7] },
  { code: 'cy', label: 'Cyprus', emoji: '🇨🇾', phone: '+357 9', phoneLengths: [7] },
  { code: 'cz', label: 'Czech Republic', emoji: '🇨🇿', phone: '+420', phoneLengths: [9] },
  { code: 'de', label: 'Germany', emoji: '🇩🇪', phone: '+49 1', phoneLengths: [9, 10] },
  { code: 'dj', label: 'Djibouti', emoji: '🇩🇯', phone: '+253 77', phoneLengths: [6] },
  { code: 'dm', label: 'Dominica', emoji: '🇩🇲', phone: '+1 767', phoneLengths: [7] },
  { code: 'dk', label: 'Denmark', emoji: '🇩🇰', phone: '+45', phoneLengths: [8] },
  { code: 'do', label: 'Dominican Republic', emoji: '🇩🇴', phone: '+1 8', phoneLengths: [9] },
  { code: 'dz', label: 'Algeria', emoji: '🇩🇿', phone: '+213', phoneLengths: [9] },
  { code: 'ec', label: 'Ecuador', emoji: '🇪🇨', phone: '+593 9', phoneLengths: [8] },
  { code: 'eg', label: 'Egypt', emoji: '🇪🇬', phone: '+20 1', phoneLengths: [9, 7] },
  { code: 'er', label: 'Eritrea', emoji: '🇪🇷', phone: '+291', phoneLengths: [7] },
  { code: 'es', label: 'Spain', emoji: '🇪🇸', phone: '+34', phoneLengths: [9] },
  { code: 'ee', label: 'Estonia', emoji: '🇪🇪', phone: '+372', phoneLengths: [7, 8] },
  { code: 'et', label: 'Ethiopia', emoji: '🇪🇹', phone: '+251 9', phoneLengths: [8] },
  { code: 'fi', label: 'Finland', emoji: '🇫🇮', phone: '+358', phoneLengths: [9, 10] },
  { code: 'fj', label: 'Fiji', emoji: '🇫🇯', phone: '+679', phoneLengths: [7] },
  { code: 'fk', label: 'Falkland Islands (Malvinas)', emoji: '🇫🇰', phone: '+500', phoneLengths: [5] },
  { code: 'fr', label: 'France', emoji: '🇫🇷', phone: '+33', phoneLengths: [9] },
  { code: 'fo', label: 'Faroe Islands', emoji: '🇫🇴', phone: '+298', phoneLengths: [6] },
  { code: 'fm', label: 'Micronesia, Federated States Of', emoji: '🇫🇲', phone: '+691', phoneLengths: [7] },
  { code: 'ga', label: 'Gabon', emoji: '🇬🇦', phone: '+241 0', phoneLengths: [7] },
  { code: 'gb', label: 'United Kingdom', emoji: '🇬🇧', phone: '+44 7', phoneLengths: [9] },
  { code: 'ge', label: 'Georgia', emoji: '🇬🇪', phone: '+995', phoneLengths: [9] },
  { code: 'gh', label: 'Ghana', emoji: '🇬🇭', phone: '+233', phoneLengths: [9] },
  { code: 'gi', label: 'Gibraltar', emoji: '🇬🇮', phone: '+350 5', phoneLengths: [7] },
  { code: 'gn', label: 'Guinea', emoji: '🇬🇳', phone: '+224 6', phoneLengths: [8] },
  { code: 'gp', label: 'Guadeloupe', emoji: '🇬🇵', phone: '+590 690', phoneLengths: [6] },
  { code: 'gm', label: 'Gambia', emoji: '🇬🇲', phone: '+220', phoneLengths: [7] },
  { code: 'gw', label: 'Guinea-Bissau', emoji: '🇬🇼', phone: '+245', phoneLengths: [7] },
  { code: 'gq', label: 'Equatorial Guinea', emoji: '🇬🇶', phone: '+240', phoneLengths: [9] },
  { code: 'gr', label: 'Greece', emoji: '🇬🇷', phone: '+30 6', phoneLengths: [9] },
  { code: 'gd', label: 'Grenada', emoji: '🇬🇩', phone: '+1 473', phoneLengths: [7] },
  { code: 'gl', label: 'Greenland', emoji: '🇬🇱', phone: '+299', phoneLengths: [6] },
  { code: 'gt', label: 'Guatemala', emoji: '🇬🇹', phone: '+502', phoneLengths: [8] },
  { code: 'gf', label: 'French Guiana', emoji: '🇬🇫', phone: '+594 694', phoneLengths: [6] },
  { code: 'gu', label: 'Guam', emoji: '🇬🇺', phone: '+1 671', phoneLengths: [7] },
  { code: 'gy', label: 'Guyana', emoji: '🇬🇾', phone: '+592 6', phoneLengths: [6] },
  { code: 'hk', label: 'Hong Kong', emoji: '🇭🇰', phone: '+852', phoneLengths: [8] },
  { code: 'hn', label: 'Honduras', emoji: '🇭🇳', phone: '+504', phoneLengths: [8] },
  { code: 'hr', label: 'Croatia', emoji: '🇭🇷', phone: '+385 9', phoneLengths: [7, 8] },
  { code: 'ht', label: 'Haiti', emoji: '🇭🇹', phone: '+509', phoneLengths: [8] },
  { code: 'hu', label: 'Hungary', emoji: '🇭🇺', phone: '+36', phoneLengths: [9] },
  { code: 'id', label: 'Indonesia', emoji: '🇮🇩', phone: '+62 8', phoneLengths: [8, 9, 10, 11] },
  { code: 'in', label: 'India', emoji: '🇮🇳', phone: '+91', phoneLengths: [10] },
  { code: 'ie', label: 'Ireland', emoji: '🇮🇪', phone: '+353 8', phoneLengths: [8] },
  { code: 'ir', label: 'Iran, Islamic Republic Of', emoji: '🇮🇷', phone: '+98 9', phoneLengths: [9] },
  { code: 'iq', label: 'Iraq', emoji: '🇮🇶', phone: '+964 7', phoneLengths: [9] },
  { code: 'is', label: 'Iceland', emoji: '🇮🇸', phone: '+354', phoneLengths: [7] },
  { code: 'il', label: 'Israel', emoji: '🇮🇱', phone: '+972 5', phoneLengths: [8] },
  { code: 'it', label: 'Italy', emoji: '🇮🇹', phone: '+39 3', phoneLengths: [8, 9] },
  { code: 'jm', label: 'Jamaica', emoji: '🇯🇲', phone: '+1 876', phoneLengths: [7] },
  { code: 'jo', label: 'Jordan', emoji: '🇯🇴', phone: '+962 7', phoneLengths: [8] },
  { code: 'jp', label: 'Japan', emoji: '🇯🇵', phone: '+81', phoneLengths: [10] },
  { code: 'kz', label: 'Kazakhstan', emoji: '🇰🇿', phone: '+7 7', phoneLengths: [9] },
  { code: 'ke', label: 'Kenya', emoji: '🇰🇪', phone: '+254 7', phoneLengths: [8] },
  { code: 'kg', label: 'Kyrgyzstan', emoji: '🇰🇬', phone: '+996', phoneLengths: [9] },
  { code: 'kh', label: 'Cambodia', emoji: '🇰🇭', phone: '+855', phoneLengths: [8, 9] },
  { code: 'ki', label: 'Kiribati', emoji: '🇰🇮', phone: '+686', phoneLengths: [5] },
  { code: 'kn', label: 'Saint Kitts And Nevis', emoji: '🇰🇳', phone: '+1 869', phoneLengths: [7] },
  { code: 'kr', label: 'Korea, Republic of', emoji: '🇰🇷', phone: '+82 1', phoneLengths: [8, 9] },
  { code: 'kw', label: 'Kuwait', emoji: '🇰🇼', phone: '+965', phoneLengths: [8] },
  { code: 'la', label: 'Lao People\'s Democratic Republic', emoji: '🇱🇦', phone: '+856 20', phoneLengths: [8] },
  { code: 'lb', label: 'Lebanon', emoji: '🇱🇧', phone: '+961', phoneLengths: [7, 8] },
  { code: 'lr', label: 'Liberia', emoji: '🇱🇷', phone: '+231', phoneLengths: [7, 8] },
  { code: 'ly', label: 'Libyan Arab Jamahiriya', emoji: '🇱🇾', phone: '+218 9', phoneLengths: [8] },
  { code: 'lc', label: 'Saint Lucia', emoji: '🇱🇨', phone: '+1 758', phoneLengths: [7] },
  { code: 'li', label: 'Liechtenstein', emoji: '🇱🇮', phone: '+423 7', phoneLengths: [6] },
  { code: 'lk', label: 'Sri Lanka', emoji: '🇱🇰', phone: '+94 7', phoneLengths: [8] },
  { code: 'ls', label: 'Lesotho', emoji: '🇱🇸', phone: '+266', phoneLengths: [8] },
  { code: 'lt', label: 'Lithuania', emoji: '🇱🇹', phone: '+370 6', phoneLengths: [7] },
  { code: 'lu', label: 'Luxembourg', emoji: '🇱🇺', phone: '+352 6', phoneLengths: [8] },
  { code: 'lv', label: 'Latvia', emoji: '🇱🇻', phone: '+371 2', phoneLengths: [7] },
  { code: 'mo', label: 'Macao', emoji: '🇲🇴', phone: '+853 6', phoneLengths: [7] },
  { code: 'ma', label: 'Morocco', emoji: '🇲🇦', phone: '+212', phoneLengths: [9] },
  { code: 'mc', label: 'Monaco', emoji: '🇲🇨', phone: '+377', phoneLengths: [8, 9] },
  { code: 'md', label: 'Moldova, Republic of', emoji: '🇲🇩', phone: '+373', phoneLengths: [8] },
  { code: 'mg', label: 'Madagascar', emoji: '🇲🇬', phone: '+261 3', phoneLengths: [8] },
  { code: 'mv', label: 'Maldives', emoji: '🇲🇻', phone: '+960', phoneLengths: [7] },
  { code: 'mx', label: 'Mexico', emoji: '🇲🇽', phone: '+52', phoneLengths: [10, 11] },
  { code: 'mh', label: 'Marshall Islands', emoji: '🇲🇭', phone: '+692', phoneLengths: [7] },
  { code: 'mk', label: 'Macedonia, the Former Yugoslav Republic Of', emoji: '🇲🇰', phone: '+389 7', phoneLengths: [7] },
  { code: 'ml', label: 'Mali', emoji: '🇲🇱', phone: '+223', phoneLengths: [8] },
  { code: 'mt', label: 'Malta', emoji: '🇲🇹', phone: '+356', phoneLengths: [8] },
  { code: 'mm', label: 'Myanmar', emoji: '🇲🇲', phone: '+95 9', phoneLengths: [7, 8, 9] },
  { code: 'me', label: 'Montenegro', emoji: '🇲🇪', phone: '+382 6', phoneLengths: [7] },
  { code: 'mn', label: 'Mongolia', emoji: '🇲🇳', phone: '+976', phoneLengths: [8] },
  { code: 'mp', label: 'Northern Mariana Islands', emoji: '🇲🇵', phone: '+1 670', phoneLengths: [7] },
  { code: 'mz', label: 'Mozambique', emoji: '🇲🇿', phone: '+258 8', phoneLengths: [8] },
  { code: 'mr', label: 'Mauritania', emoji: '🇲🇷', phone: '+222', phoneLengths: [8] },
  { code: 'ms', label: 'Montserrat', emoji: '🇲🇸', phone: '+1 664', phoneLengths: [7] },
  { code: 'mq', label: 'Martinique', emoji: '🇲🇶', phone: '+596 696', phoneLengths: [6] },
  { code: 'mu', label: 'Mauritius', emoji: '🇲🇺', phone: '+230 5', phoneLengths: [7] },
  { code: 'mw', label: 'Malawi', emoji: '🇲🇼', phone: '+265', phoneLengths: [9] },
  { code: 'my', label: 'Malaysia', emoji: '🇲🇾', phone: '+60', phoneLengths: [9, 10, 8] },
  { code: 'yt', label: 'Mayotte', emoji: '🇾🇹', phone: '+262 639', phoneLengths: [6] },
  { code: 'na', label: 'Namibia', emoji: '🇳🇦', phone: '+264', phoneLengths: [9] },
  { code: 'nc', label: 'New Caledonia', emoji: '🇳🇨', phone: '+687', phoneLengths: [6] },
  { code: 'ne', label: 'Niger', emoji: '🇳🇪', phone: '+227 9', phoneLengths: [7] },
  { code: 'nf', label: 'Norfolk Island', emoji: '🇳🇫', phone: '+672', phoneLengths: [5] },
  { code: 'ng', label: 'Nigeria', emoji: '🇳🇬', phone: '+234', phoneLengths: [10] },
  { code: 'ni', label: 'Nicaragua', emoji: '🇳🇮', phone: '+505 8', phoneLengths: [7] },
  { code: 'nu', label: 'Niue', emoji: '🇳🇺', phone: '+683', phoneLengths: [4] },
  { code: 'nl', label: 'Netherlands', emoji: '🇳🇱', phone: '+31 6', phoneLengths: [8] },
  { code: 'no', label: 'Norway', emoji: '🇳🇴', phone: '+47', phoneLengths: [8] },
  { code: 'np', label: 'Nepal', emoji: '🇳🇵', phone: '+977 9', phoneLengths: [9] },
  { code: 'nr', label: 'Nauru', emoji: '🇳🇷', phone: '+674 555', phoneLengths: [4] },
  { code: 'nz', label: 'New Zealand', emoji: '🇳🇿', phone: '+64', phoneLengths: [8, 9, 10] },
  { code: 'om', label: 'Oman', emoji: '🇴🇲', phone: '+968 9', phoneLengths: [7] },
  { code: 'pk', label: 'Pakistan', emoji: '🇵🇰', phone: '+92 3', phoneLengths: [9] },
  { code: 'pa', label: 'Panama', emoji: '🇵🇦', phone: '+507 6', phoneLengths: [7] },
  { code: 'pe', label: 'Peru', emoji: '🇵🇪', phone: '+51', phoneLengths: [9, 8] },
  { code: 'ph', label: 'Philippines', emoji: '🇵🇭', phone: '+63 9', phoneLengths: [9] },
  { code: 'pw', label: 'Palau', emoji: '🇵🇼', phone: '+680', phoneLengths: [7] },
  { code: 'pg', label: 'Papua New Guinea', emoji: '🇵🇬', phone: '+675 7', phoneLengths: [7] },
  { code: 'pl', label: 'Poland', emoji: '🇵🇱', phone: '+48', phoneLengths: [9] },
  { code: 'pr', label: 'Puerto Rico', emoji: '🇵🇷', phone: '+1', phoneLengths: [10] },
  { code: 'pt', label: 'Portugal', emoji: '🇵🇹', phone: '+351 9', phoneLengths: [8] },
  { code: 'py', label: 'Paraguay', emoji: '🇵🇾', phone: '+595 9', phoneLengths: [8] },
  { code: 'ps', label: 'Palestinian Territory, Occupied', emoji: '🇵🇸', phone: '+970 5', phoneLengths: [8] },
  { code: 'pf', label: 'French Polynesia', emoji: '🇵🇫', phone: '+689 8', phoneLengths: [7] },
  { code: 'qa', label: 'Qatar', emoji: '🇶🇦', phone: '+974', phoneLengths: [8] },
  { code: 're', label: 'Réunion', emoji: '🇷🇪', phone: '+262 69', phoneLengths: [7] },
  { code: 'ro', label: 'Romania', emoji: '🇷🇴', phone: '+40 7', phoneLengths: [8] },
  { code: 'ru', label: 'Russian Federation', emoji: '🇷🇺', phone: '+7', phoneLengths: [10] },
  { code: 'rw', label: 'Rwanda', emoji: '🇷🇼', phone: '+250 7', phoneLengths: [8] },
  { code: 'sa', label: 'Saudi Arabia', emoji: '🇸🇦', phone: '+966 5', phoneLengths: [8] },
  { code: 'sd', label: 'Sudan', emoji: '🇸🇩', phone: '+249 9', phoneLengths: [8] },
  { code: 'ss', label: 'South Sudan', emoji: '🇸🇸', phone: '+211 9', phoneLengths: [8] },
  { code: 'sn', label: 'Senegal', emoji: '🇸🇳', phone: '+221 7', phoneLengths: [8] },
  { code: 'sg', label: 'Singapore', emoji: '🇸🇬', phone: '+65', phoneLengths: [8] },
  { code: 'sh', label: 'Saint Helena', emoji: '🇸🇭', phone: '+290', phoneLengths: [4] },
  { code: 'sj', label: 'Svalbard And Jan Mayen', emoji: '🇸🇯', phone: '+47', phoneLengths: [8] },
  { code: 'sb', label: 'Solomon Islands', emoji: '🇸🇧', phone: '+677', phoneLengths: [7] },
  { code: 'sl', label: 'Sierra Leone', emoji: '🇸🇱', phone: '+232', phoneLengths: [8] },
  { code: 'sv', label: 'El Salvador', emoji: '🇸🇻', phone: '+503 7', phoneLengths: [7] },
  { code: 'sm', label: 'San Marino', emoji: '🇸🇲', phone: '+378', phoneLengths: [10] },
  { code: 'so', label: 'Somalia', emoji: '🇸🇴', phone: '+252 9', phoneLengths: [7] },
  { code: 'sx', label: 'Sint Maarten', emoji: '🇸🇽', phone: '+1 721', phoneLengths: [7] },
  { code: 'pm', label: 'Saint Pierre And Miquelon', emoji: '🇵🇲', phone: '+508 55', phoneLengths: [4] },
  { code: 'rs', label: 'Serbia', emoji: '🇷🇸', phone: '+381 6', phoneLengths: [7, 8] },
  { code: 'st', label: 'Sao Tome and Principe', emoji: '🇸🇹', phone: '+239 9', phoneLengths: [6] },
  { code: 'sr', label: 'Suriname', emoji: '🇸🇷', phone: '+597', phoneLengths: [7] },
  { code: 'sk', label: 'Slovakia', emoji: '🇸🇰', phone: '+421 9', phoneLengths: [8] },
  { code: 'si', label: 'Slovenia', emoji: '🇸🇮', phone: '+386', phoneLengths: [8] },
  { code: 'se', label: 'Sweden', emoji: '🇸🇪', phone: '+46 7', phoneLengths: [8] },
  { code: 'sc', label: 'Seychelles', emoji: '🇸🇨', phone: '+248 2', phoneLengths: [6] },
  { code: 'sy', label: 'Syrian Arab Republic', emoji: '🇸🇾', phone: '+963 9', phoneLengths: [8] },
  { code: 'tc', label: 'Turks and Caicos Islands', emoji: '🇹🇨', phone: '+1 649', phoneLengths: [7] },
  { code: 'td', label: 'Chad', emoji: '🇹🇩', phone: '+235', phoneLengths: [8] },
  { code: 'tg', label: 'Togo', emoji: '🇹🇬', phone: '+228 9', phoneLengths: [7] },
  { code: 'th', label: 'Thailand', emoji: '🇹🇭', phone: '+66', phoneLengths: [9] },
  { code: 'tj', label: 'Tajikistan', emoji: '🇹🇯', phone: '+992 9', phoneLengths: [8] },
  { code: 'tk', label: 'Tokelau', emoji: '🇹🇰', phone: '+690', phoneLengths: [4] },
  { code: 'tm', label: 'Turkmenistan', emoji: '🇹🇲', phone: '+993 6', phoneLengths: [7] },
  { code: 'tl', label: 'Timor-Leste', emoji: '🇹🇱', phone: '+670 7', phoneLengths: [7] },
  { code: 'to', label: 'Tonga', emoji: '🇹🇴', phone: '+676', phoneLengths: [5] },
  { code: 'tt', label: 'Trinidad and Tobago', emoji: '🇹🇹', phone: '+1 868', phoneLengths: [7] },
  { code: 'tn', label: 'Tunisia', emoji: '🇹🇳', phone: '+216', phoneLengths: [8] },
  { code: 'tr', label: 'Turkey', emoji: '🇹🇷', phone: '+90 5', phoneLengths: [9] },
  { code: 'tv', label: 'Tuvalu', emoji: '🇹🇻', phone: '+688', phoneLengths: [5] },
  { code: 'tw', label: 'Taiwan', emoji: '🇹🇼', phone: '+886 9', phoneLengths: [8] },
  { code: 'tz', label: 'Tanzania, United Republic of', emoji: '🇹🇿', phone: '+255', phoneLengths: [9] },
  { code: 'ug', label: 'Uganda', emoji: '🇺🇬', phone: '+256 7', phoneLengths: [8] },
  { code: 'ua', label: 'Ukraine', emoji: '🇺🇦', phone: '+380', phoneLengths: [9] },
  { code: 'uy', label: 'Uruguay', emoji: '🇺🇾', phone: '+598 9', phoneLengths: [7] },
  { code: 'uz', label: 'Uzbekistan', emoji: '🇺🇿', phone: '+998 9', phoneLengths: [8] },
  { code: 'vc', label: 'Saint Vincent And The Grenedines', emoji: '🇻🇨', phone: '+1 784', phoneLengths: [7] },
  { code: 've', label: 'Venezuela, Bolivarian Republic of', emoji: '🇻🇪', phone: '+58 4', phoneLengths: [9] },
  { code: 'vg', label: 'Virgin Islands, British', emoji: '🇻🇬', phone: '+1 284', phoneLengths: [7] },
  { code: 'vi', label: 'Virgin Islands, U.S.', emoji: '🇻🇮', phone: '+1 340', phoneLengths: [7] },
  { code: 'vn', label: 'Viet Nam', emoji: '🇻🇳', phone: '+84', phoneLengths: [8, 9] },
  { code: 'vu', label: 'Vanuatu', emoji: '🇻🇺', phone: '+678', phoneLengths: [7] },
  { code: 'wf', label: 'Wallis and Futuna', emoji: '🇼🇫', phone: '+681', phoneLengths: [6] },
  { code: 'ws', label: 'Samoa', emoji: '🇼🇸', phone: '+685 7', phoneLengths: [6] },
  { code: 'ye', label: 'Yemen', emoji: '🇾🇪', phone: '+967 7', phoneLengths: [8] },
  { code: 'za', label: 'South Africa', emoji: '🇿🇦', phone: '+27', phoneLengths: [9] },
  { code: 'zm', label: 'Zambia', emoji: '🇿🇲', phone: '+260 9', phoneLengths: [8] },
  { code: 'zw', label: 'Zimbabwe', emoji: '🇿🇼', phone: '+263 7', phoneLengths: [8] },
  { code: '', label: 'Other', emoji: '🌏', phone: '+', phoneLengths: [] },
];

export default rawCountries.map(({ phoneLengths, ...country }): Country => {
  const phoneFormats: Array<string | number> = [];

  phoneLengths.forEach((length) => {
    phoneFormats.push(length, getFormatForLength(length));
  });

  return phoneFormats.length ? { ...country, phoneFormats } : country;
});
